[tool.poetry]
name = "retroarcherdiscord-bot"
version = "0.1.0"
description = ""
authors = ["ReenigneArcher <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.3"
Flask = "^2.0.1"
discord-py-slash-command = "^2.0.0"
requests = "^2.25.1"
Markdown = "^3.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
