[tool.poetry]
name = "retroarcherdiscord-bot"
version = "0.1.0"
description = "Bot for RetroArcher discord server"
authors = ["ReenigneArcher"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "1.7.3"
discord-py-slash-command = "3.0.3"
Flask = "2.0.2"
python-dotenv = "0.19.2"
requests = "2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
